# Generated by Django 2.2.5 on 2021-05-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racket_name', models.CharField(max_length=30, verbose_name='ラケット名')),
                ('brand', models.CharField(choices=[('YONEX', 'YONEX'), ('MIZUNO', 'MIZUNO'), ('DUNLOP', 'DUNLOP'), ('その他', 'その他')], max_length=30, verbose_name='ブランド')),
                ('recommend_position', models.CharField(choices=[('後衛', '後衛'), ('前衛', '前衛')], max_length=5, verbose_name='ポジション')),
                ('color', models.CharField(max_length=50, verbose_name='色名')),
                ('release_date', models.DateField(verbose_name='発売日')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='本文')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
