# Generated by Django 2.2.5 on 2021-11-27 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='アイテム名')),
                ('item_url_name', models.CharField(default=False, max_length=30, verbose_name='アイテムurl表示名')),
                ('slug', models.SlugField(null=True, verbose_name='URL表示名')),
                ('brand_name', models.CharField(choices=[('YONEX', 'YONEX'), ('MIZUNO', 'MIZUNO'), ('DUNLOP', 'DUNLOP'), ('GOSEN', 'GOSEN'), ('SRIXON', 'SRIXON')], default=False, max_length=20, verbose_name='ブランド名')),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='アイテム画像')),
                ('item_position', models.CharField(choices=[('後衛', '後衛'), ('前衛', '前衛'), ('前・後衛', '前・後衛')], default=False, max_length=5, verbose_name='ポジション')),
                ('release_date', models.DateField(verbose_name='発売月')),
                ('display', models.BooleanField(default=False, verbose_name='表示')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, verbose_name='URLスラッグ（英語）')),
                ('text', models.TextField(max_length=200, verbose_name='本文')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
