# Generated by Django 3.2.7 on 2022-02-08 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, verbose_name='アイテム名')),
                ('slug', models.SlugField(max_length=30, null=True, verbose_name='URL表示名')),
                ('brand_name', models.CharField(choices=[('YONEX', 'YONEX'), ('MIZUNO', 'MIZUNO'), ('DUNLOP', 'DUNLOP')], default=False, max_length=20, verbose_name='ブランド名')),
                ('series_name', models.CharField(choices=[('VOLTRAGE', 'VOLTRAGE'), ('GEOBREAK', 'GEOBREAK'), ('F-LASER', 'F-LASER'), ('YONEX_OTHERS', 'YONEX_OTHERS'), ('SCUD', 'SCUD'), ('DIOS', 'DIOS'), ('MIZUNO_OTHERS', 'MIZUNO_OTHERS'), ('GALAXEED', 'GALAXEED'), ('JETSTORM', 'JETSTORM'), ('DUNLOP_OTHERS', 'DUNLOP_OTHERS')], default=False, max_length=20, verbose_name='シリーズ名')),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='アイテム画像')),
                ('item_position', models.CharField(choices=[('後衛', '後衛'), ('前衛', '前衛'), ('前・後衛', '前・後衛')], default=False, max_length=5, verbose_name='ポジション')),
                ('release_date', models.DateField(verbose_name='発売月')),
                ('display', models.BooleanField(default=False, verbose_name='表示')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='本文')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.BooleanField(default=False, verbose_name='編集済み')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
