# Generated by Django 3.2.7 on 2022-01-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='編集済み'),
        ),
    ]
