# Generated by Django 2.2.5 on 2021-06-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_productmodel_racket_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='racket_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='ラケット写真'),
        ),
    ]
