# Generated by Django 2.2.5 on 2021-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20210627_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='本文'),
        ),
    ]
