# Generated by Django 2.2.5 on 2021-06-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20210627_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='本文'),
        ),
    ]
