# Generated by Django 2.2.5 on 2021-07-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_auto_20210628_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='racket_url_name',
            field=models.CharField(default=1, max_length=30, verbose_name='ラケットurl表示名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.CharField(choices=[('YONEX', 'YONEX'), ('MIZUNO', 'MIZUNO'), ('DUNLOP', 'DUNLOP'), ('GOSEN', 'GOSEN'), ('SRIXON', 'SRIXON')], max_length=30, verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='recommend_position',
            field=models.CharField(choices=[('後衛', '後衛'), ('前衛', '前衛'), ('両用', '両用')], max_length=5, verbose_name='ポジション'),
        ),
    ]
