# Generated by Django 2.2.5 on 2021-07-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_auto_20210702_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URLスラッグ（英語）'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URLスラッグ（英語）'),
        ),
    ]
