# Generated by Django 2.2.5 on 2021-07-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0013_auto_20210711_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
