# Generated by Django 2.2.5 on 2021-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0018_like_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='本文'),
        ),
    ]
