# Generated by Django 2.2.5 on 2021-10-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0019_auto_20210923_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=200, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='recommend_position',
            field=models.CharField(choices=[('後衛', '後衛'), ('前衛', '前衛'), ('前・後衛', '前・後衛')], max_length=5, verbose_name='ポジション'),
        ),
    ]
