# Generated by Django 2.2.5 on 2021-11-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0022_auto_20211011_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Item',
        ),
    ]
