# Generated by Django 2.2.5 on 2021-11-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0023_auto_20211110_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='product_id',
            new_name='item',
        ),
    ]
