# Generated by Django 2.2.5 on 2021-11-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0024_auto_20211110_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='racket_photo',
        ),
        migrations.AddField(
            model_name='item',
            name='brand_name',
            field=models.CharField(choices=[('YONEX', 'YONEX'), ('MIZUNO', 'MIZUNO'), ('DUNLOP', 'DUNLOP'), ('GOSEN', 'GOSEN'), ('SRIXON', 'SRIXON')], default='YONEX', max_length=20, verbose_name='ブランド名'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='アイテム画像'),
        ),
    ]
