# Generated by Django 2.2.5 on 2021-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0026_auto_20211110_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='recommend_position',
        ),
        migrations.AddField(
            model_name='item',
            name='item_position',
            field=models.CharField(choices=[('後衛', '後衛'), ('前衛', '前衛'), ('前・後衛', '前・後衛')], default=False, max_length=5, verbose_name='ポジション'),
        ),
    ]
