# Generated by Django 2.2.5 on 2021-11-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0027_auto_20211110_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='racket_name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default=False, max_length=30, verbose_name='アイテム名'),
        ),
    ]
