# Generated by Django 2.2.5 on 2021-11-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0028_auto_20211110_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='racket_url_name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_url_name',
            field=models.CharField(default='未設定', max_length=30, verbose_name='ラケットurl表示名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='未設定', max_length=30, verbose_name='アイテム名'),
        ),
    ]
