# Generated by Django 2.2.5 on 2021-11-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0030_auto_20211110_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=30, verbose_name='アイテム名'),
        ),
    ]
