# Generated by Django 2.2.5 on 2021-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0031_auto_20211110_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_url_name',
            field=models.CharField(default=False, max_length=30, verbose_name='アイテムurl表示名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL表示名'),
        ),
    ]
