# Generated by Django 2.2.5 on 2021-11-10 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0032_auto_20211110_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='session',
        ),
        migrations.AlterField(
            model_name='item',
            name='release_date',
            field=models.DateField(verbose_name='発売月'),
        ),
        migrations.AlterField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
