# Generated by Django 2.2.5 on 2021-11-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0033_auto_20211110_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-timestamp']},
        ),
    ]
