# Generated by Django 2.2.5 on 2021-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('description', models.TextField(blank=True, max_length=120, null=True, verbose_name='プロフィール')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真')),
                ('age', models.CharField(blank=True, choices=[('12歳以下', '12歳以下'), ('13歳', '13歳'), ('14歳', '14歳'), ('15歳', '15歳'), ('16歳', '16歳'), ('17歳', '17歳'), ('18歳', '18歳'), ('19歳~20歳', '19歳~20歳'), ('21歳~22歳', '21歳~22歳'), ('23歳~25歳', '23歳~25歳'), ('26歳~29歳', '26歳~29歳'), ('30歳~39歳', '30歳~39歳'), ('40歳~49歳', '40歳~49歳'), ('50歳~59歳', '50歳~59歳'), ('60歳~69歳', '60歳~69歳'), ('70歳以上', '70歳以上')], max_length=30, null=True, verbose_name='年齢')),
                ('gender', models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性')], max_length=15, null=True, verbose_name='性別')),
                ('history', models.CharField(blank=True, choices=[('1年未満', '1年未満'), ('1年以上3年未満', '1年以上3年未満'), ('3年以上6年未満', '3年以上6年未満'), ('6年以上8年未満', '6年以上8年未満'), ('8年以上10年未満', '8年以上10年未満'), ('10年以上', '10年以上')], max_length=25, null=True, verbose_name='競技経験年数')),
                ('activity_area', models.CharField(blank=True, choices=[('北海道', '北海道'), ('東北', '東北'), ('関東', '関東'), ('中部', '中部'), ('近畿', '近畿'), ('中国', '中国'), ('四国', '四国'), ('九州', '九州'), ('その他', 'その他')], max_length=5, null=True, verbose_name='活動エリア')),
                ('position', models.CharField(blank=True, choices=[('後衛', '後衛'), ('前衛', '前衛')], max_length=5, null=True, verbose_name='ポジション')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'CustomUser',
            },
        ),
    ]
