# Generated by Django 2.2.5 on 2021-05-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity_area',
            field=models.CharField(blank=True, choices=[('北海道', '北海道'), ('東北', '東北'), ('関東', '関東'), ('中部', '中部'), ('近畿', '近畿'), ('中国', '中国'), ('四国', '四国'), ('九州', '九州'), ('その他', 'その他')], max_length=5, null=True, verbose_name='活動エリア'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性')], max_length=15, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='history',
            field=models.CharField(blank=True, choices=[('1年未満', '1年未満'), ('1年以上3年未満', '1年以上3年未満'), ('3年以上6年未満', '3年以上6年未満'), ('6年以上8年未満', '6年以上8年未満'), ('8年以上10年未満', '8年以上10年未満'), ('10年以上', '10年以上')], max_length=5, null=True, verbose_name='競技経験年数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('後衛', '後衛'), ('前衛', '前衛')], max_length=5, null=True, verbose_name='ポジション'),
        ),
    ]
