# Generated by Django 2.2.5 on 2021-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210511_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(blank=True, choices=[('12歳以下', '12歳以下'), ('13歳', '13歳'), ('14歳', '14歳'), ('15歳', '15歳'), ('16歳', '16歳'), ('17歳', '17歳'), ('18歳', '18歳'), ('19歳~20歳', '19歳~20歳'), ('21歳~22歳', '21歳~22歳'), ('23歳~25歳', '23歳~25歳'), ('26歳~29歳', '26歳~29歳'), ('30歳~39歳', '30歳~39歳'), ('40歳~49歳', '40歳~49歳'), ('50歳~59歳', '50歳~59歳'), ('60歳~69歳', '60歳~69歳'), ('70歳以上', '70歳以上')], max_length=30, null=True, verbose_name='年齢'),
        ),
    ]
