# Generated by Django 2.2.5 on 2021-10-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210728_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='プロフィール'),
        ),
    ]
